### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by xSerpentineX** [thegamerx1/wakeonlan#1]
Hello darkness, my old friend;
I've come to talk with you again
because a vision softly creeping
left its seeds while I was sleeping
and the vision that was planted in my brain
still remains
within the sound of silence.

In restless dreams I walked alone;
narrow streets of cobblestone.
'Neath the halo of a street lamp
I turned my collar to the cold and damp
when my eyes were stabbed by the flash of a neon light
that split the night
and touched the sound of silence.

And in the naked light I saw
ten thousand people, maybe more.
People talking without speaking,
people hearing without listening,
people writing songs that voices never share;
no one dared
disturb the sound of silence.

"Fools" said I, "You do not know
silence like a cancer grows.
Hear my words that I might teach you,
take my arms that I might reach you"
but my words like silent raindrops fell
and echoed in the wells of silence.

And the people bowed and prayed
to the neon god they made.
And the sign flashed out its warning,
in the words that it was forming,
and the sign said, "The words of the prophets
are written on the subway walls
and tenement halls
and whispered in the sounds of silence."

**Comment by thegamerx1** [comment]
what is this for?

**Comment by xSerpentineX** [comment]
Just saying hello to an old friend.

**Comment by thegamerx1** [comment]
Hello
